language: go
sudo: false
go:
  - 1.3
  - 1.4
  - 1.5
install:
  - go get golang.org/x/tools/cmd/vet
  - make deps
script:
  - >
    [ "${TRAVIS_PULL_REQUEST}" = "false" ]
    && make fmt vet testall
    || make fmt vet test
